default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 6000
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("DB_USER") { 'admin' } %>
  password: <%= ENV.fetch("DB_PASS") { 'admin' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'municipe_web' } %>

test:
  <<: *default
  database: 'municipe_web_test'

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME") { 'municipe_web_prod' } %>
